### ISSUE TITLE
Error when installing Superset Utility

### ISSUE THREAD

**Issue by EJOOSTEROP** [meltano/superset-ext#10]
I am not sure this is the right place (I tried the Meltano Stack channel), but here it goes.

# Expected result
Successful install of the Superset Utility using Meltano.

# Actual Result
![image](https://user-images.githubusercontent.com/49541561/233506321-25baab9b-213e-4921-9171-dee208e0a767.png)

# Replicate
Invoke `meltano add utility superset`. For a totally clean example:
```shell
docker run -v meltano_test:/project --entrypoint "/bin/bash" meltano/meltano:v2.17.1-python3.9 -c "meltano init test_meltano; cd test_meltano; meltano add utility superset"
```

# Workaround
Use the Apache variant. In meltano.yml:
```yaml
  utilities:
  - name: superset
    variant: apache
    pip_url: apache-superset==2.0.0 flask==2.0.3 werkzeug==2.0.3 jinja2==3.0.1 wtforms==2.3.3
      cryptography==3.4.7
      markupsafe==2.0.1
```
